name: Praiyder SCA Scan

on:
  push:
    branches:
      - main

jobs:
  sca-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Praiyder Analysis
        uses: praiyder/sca-action@latest
        with:
          args: scan
